nombre = "Jonathan Morales Salazar"
print(nombre.lower())
print(nombre.islower())
print(nombre.upper())
print(nombre.isupper())
print(nombre.title())
print(nombre.istitle())
print(nombre.swapcase())
print(nombre.capitalize())
print(nombre.center(100))
print(nombre.center(100, '='))
print(nombre.ljust(100))
print(nombre.ljust(100, '='))
print(nombre.rjust(100))
print(nombre.rjust(100, '='))
print(nombre.count('a'))
print(nombre.count('a', 8, 20))
print(nombre.startswith('Jon'))
print(nombre.endswith('zar'))
print(nombre[9:14])
print(nombre[::3])
print(nombre.find('Moral'))